type Query {
  """Database identifier that should be skipped"""
  id: ID!

  """Unique identifier for the user"""
  userId: ID!

  """Display name shown in the UI"""
  displayName: String!

  """Primary contact email address"""
  email: String!
}
